name: CI/CD

on:
  push:
    branches: 
      - master
      - readable-workflow
      - use-option

jobs:
  func-build:
    runs-on: ubuntu-latest
    container:
      image: openfaas/faas-cli:latest-root
      options: -v /github/home:/root:rw -v `pwd`:`pwd`:rw
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pull template
        run: faas-cli template store pull golang-http