name: CI/CD

on:
  push:
    branches: 
      - master
      - readable-workflow
      - use-option

jobs:
  func-build:
    runs-on: ubuntu-latest
    container:
      image: openfaas/faas-cli:latest-root
      options: -v $HOME:/root:rw -v `pwd`:`pwd`
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pull template
        with:
          args: template store pull golang-http
      # - 
      #   name: Running faas-cli skrinkwrap build
      #   uses: docker://openfaas/faas-cli:latest-root
      #   with:
      #     entrypoint: faas-cli
      #     args: build -f faasd-hello.yml --shrinkwrap
      # -
      #   name: Login to DockerHub
      #   if: success()
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - 
      #   name: Login to OpenFaaS Gateway
      #   uses: docker://openfaas/faas-cli:latest-root
      #   with:
      #     entrypoint: faas-cli
      #     args: |
      #       login -p ${{ secrets.OPENFAAS_GATEWAY_PASSWD }} -g ${{ secrets.OPENFAAS_GATEWAY }}
      # - 
      #   name: Update permissions to build and .openfaas directories
      #   run: |
      #     sudo chown $USER:$USER -R build/ $HOME/.openfaas
      # - 
      #   name: Build and Push the OpenFaaS function
      #   run: |
      #     docker build --tag utssavanand2/faasd-hello:latest \
      #     build/faasd-hello/ && \
      #     docker push utsavanand2/faasd-hello:latest
      # -
      #   name: Deploying the OpenFaaS function to your faasd appliance
      #   uses: docker://openfaas/faas-cli:latest-root
      #   with:
      #     entrypoint: faas-cli
      #     args: |
      #       deploy -f faasd-hello.yml
