name: CI/CD

on:
  push:
    branches: 
      - master
      - readable-workflow
      - use-option

jobs:
  func-build:
    runs-on: ubuntu-latest
    container:
      image: openfaas/faas-cli:latest-root
      options: -v $HOME:/root:rw -v `pwd`:`pwd`
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Pull template
        with:
          entrypoint: faas-cli
        run: template store pull golang-http